[package]
name = "conner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
log = "0.4.17"
env_logger = "0.9.0"
nix = "0.25.0"
scan_fmt = "0.2.6"