version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo:4.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"