// mod arrays;
// mod conditionals;
// mod enums;
// mod functions;
// mod loops;
// mod generic_bounds;
// mod ownership_borrowing;
// mod pointer_ref;
// mod strings;
// mod structs;
// mod tuples;
// mod types;
// mod vars;
// mod vectors;
// mod macro_rules;
// mod lifetimes;
mod traits;
// mod linked_list;
// mod smart_pointer;

fn main() {
    // vars::run();
    // types::run();
    // strings::run();
    // tuples::run();
    // conditionals::run();
    // arrays::run();
    // vectors::run();
    // loops::run();
    // functions::run();
    // enums::run();
    // structs::run();
    // pointer_ref::run();
    // ownership_borrowing::run();
    // generic_bounds::run();
    // macro_rules::run();
    // lifetimes::run();
    traits::run();
    // linked_list::run();
    // smart_pointer::run();
}
